kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: registry.crazycow.ninja/crazycow
      tags: 1
      registry: registry.crazycow.ninja
      username:
        from_secret: registry-user
      password:
        from_secret: registry-password
      build_args:
        - REDIRECT_URL=https://crazycow.ninja/callback
        - AUTH0_CLIENT_ID=d6o9hoP4niAGPT2tlVbaUCmu51epafKS
        - AUTH0_DOMAIN=mostlind.auth0.com
        - BACKEND_URL=https://api.crazycow.ninja/
    when:
      branch:
        - master
      event:
        - push
